### ISSUE TITLE
Forge Couple errors after Forge last updates

### ISSUE THREAD

**Issue by ostap667inbox** [Haoming02/sd-forge-couple#42]
```
---
*** Error calling: F:\stable-diffusion-webui-forge\extensions\sd-forge-couple\scripts\forge_couple.py/ui
    Traceback (most recent call last):
      File "F:\stable-diffusion-webui-forge\modules\scripts.py", line 545, in wrap_call
        return func(*args, **kwargs)
      File "F:\stable-diffusion-webui-forge\extensions\sd-forge-couple\scripts\forge_couple.py", line 33, in ui
        return couple_UI(self, is_img2img, f"{self.title()} v{VERSION}")
      File "F:\stable-diffusion-webui-forge\extensions\sd-forge-couple\scripts\couple_ui.py", line 150, in couple_UI
        real_preview_btn.click(
    TypeError: EventListener._setup.<locals>.event_trigger() got an unexpected keyword argument '_js'

---
```

Do you plan to adapt Forge Couple for the updated Forge?

**Comment by Haoming02** [comment]
Aye, already know how to fix it.

Just trying to figure out a way to have both version co-existing, without having to make a new branch or something,

**Comment by Haoming02** [comment]
The `Basic` mode now works

The `Advanced` mode is apparently broken. It was empty when I switch to it XD

Will investigate more tomorrow...

**Comment by Haoming02** [comment]
Please give the [`revamp`](https://github.com/Haoming02/sd-forge-couple/tree/revamp) branch a try!

**Comment by EveKaczmarek** [comment]
lllyasviel is actively working on the backend at the moment. I'd recommend to back off until the new backend is 100% complete. Which, judging by the commit notes, will happen pretty soon. As of now (https://github.com/lllyasviel/stable-diffusion-webui-forge/commit/cfe91791025511af46e8f5e08a3b98656f1a032d), Forge Couple throws the following error when running generation:

```
*** Error running process_before_every_sampling: /home/Forge/extensions/sd-forge-couple/scripts/forge_couple.py
    Traceback (most recent call last):
      File "/home/Forge/modules/scripts.py", line 892, in process_before_every_sampling
        script.process_before_every_sampling(p, *script_args, **kwargs)
      File "/home/Forge/extensions/sd-forge-couple/scripts/forge_couple.py", line 211, in process_before_every_sampling
        patched_unet = forgeAttentionCouple.patch_unet(unet, base_mask, ARGs)
      File "/home/Forge/venv/lib/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "/home/Forge/extensions/sd-forge-couple/couple/attention_couple.py", line 19, in patch_unet
        dtype = new_model.model.diffusion_model.dtype
      File "/home/Forge/venv/lib/site-packages/torch/nn/modules/module.py", line 1709, in __getattr__
        raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
    AttributeError: 'IntegratedUNet2DConditionModel' object has no attribute 'dtype'
```

**Comment by EveKaczmarek** [comment]
Also, for some reason, the selection is much larger than the actual mapping area. Around 15% in both directions.
Browser is Firefox 128.

![image](https://github.com/user-attachments/assets/f181d22f-0853-4307-9792-7d5d9ec777ba)

**Comment by Haoming02** [comment]
> the selection is much larger than the actual mapping area

Huh. I just tried it and it's broken on **Edge** too, but only for Gradio 4. It works correctly on old Forge.
