### ISSUE TITLE
ImportError: cannot import name 'memory_management' from 'backend' (unknown location)

### ISSUE THREAD

**Issue by 4KsTan** [Haoming02/sd-forge-couple#53]
### Issue ：

```
*** Error loading script: forge_couple.py
    Traceback (most recent call last):
      File "D:\stable-diffusion-webui-reForge\modules\scripts.py", line 524, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\stable-diffusion-webui-reForge\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\stable-diffusion-webui-reForge\extensions\sd-forge-couple\scripts\forge_couple.py", line 15, in <module>
        from lib_couple.attention_couple import AttentionCouple
      File "D:\stable-diffusion-webui-reForge\extensions\sd-forge-couple\lib_couple\attention_couple.py", line 13, in <module>
        from backend import memory_management
    ImportError: cannot import name 'memory_management' from 'backend' (unknown location)
```

Hi，I having some problem with
checkpoint ：reforge [main](https://github.com/Panchovix/stable-diffusion-webui-reForge)
commit：[3722371](https://github.com/Panchovix/stable-diffusion-webui-reForge/commit/372237113a53d2414a8a06dfc6bc267d8f90c5c3)

**Comment by 4KsTan** [comment]
thank you so much，it worked
