### ISSUE TITLE
Issue with Hires.fix + LayerDiffusion

### ISSUE THREAD

**Issue by Thyranix** [Haoming02/sd-forge-couple#71]
Trying to create images with Couple enabled and LayerDiffusion (https://github.com/lllyasviel/sd-forge-layerdiffuse) to make the background transparent works only without hires enabled.
When I enable hires the generation stops once its trys to enhance the image.

the following error gets logged when that happens:
```
Traceback (most recent call last):
  File "D:\stable-diffusion\stable-diffusion-webui-forge-new\webui\modules_forge\main_thread.py", line 30, in work
    self.result = self.func(*self.args, **self.kwargs)
  File "D:\stable-diffusion\stable-diffusion-webui-forge-new\webui\modules\txt2img.py", line 125, in txt2img_function
    processed = processing.process_images(p)
  File "D:\stable-diffusion\stable-diffusion-webui-forge-new\webui\modules\processing.py", line 842, in process_images
    res = process_images_inner(p)
  File "D:\stable-diffusion\stable-diffusion-webui-forge-new\webui\modules\processing.py", line 988, in process_images_inner
    samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
  File "D:\stable-diffusion\stable-diffusion-webui-forge-new\webui\modules\processing.py", line 1427, in sample
    return self.sample_hr_pass(samples, decoded_samples, seeds, subseeds, subseed_strength, prompts)
  File "D:\stable-diffusion\stable-diffusion-webui-forge-new\webui\modules\processing.py", line 1531, in sample_hr_pass
    samples = self.sampler.sample_img2img(self, samples, noise, self.hr_c, self.hr_uc, steps=self.hr_second_pass_steps or self.steps, image_conditioning=image_conditioning)
  File "D:\stable-diffusion\stable-diffusion-webui-forge-new\webui\modules\sd_samplers_kdiffusion.py", line 188, in sample_img2img
    samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "D:\stable-diffusion\stable-diffusion-webui-forge-new\webui\modules\sd_samplers_common.py", line 272, in launch_sampling
    return func()
  File "D:\stable-diffusion\stable-diffusion-webui-forge-new\webui\modules\sd_samplers_kdiffusion.py", line 188, in <lambda>
    samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "D:\stable-diffusion\stable-diffusion-webui-forge-new\system\python\lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "D:\stable-diffusion\stable-diffusion-webui-forge-new\webui\k_diffusion\sampling.py", line 146, in sample_euler_ancestral
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "D:\stable-diffusion\stable-diffusion-webui-forge-new\system\python\lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\stable-diffusion\stable-diffusion-webui-forge-new\system\python\lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\stable-diffusion\stable-diffusion-webui-forge-new\webui\modules\sd_samplers_cfg_denoiser.py", line 199, in forward
    denoised, cond_pred, uncond_pred = sampling_function(self, denoiser_params=denoiser_params, cond_scale=cond_scale, cond_composition=cond_composition)
  File "D:\stable-diffusion\stable-diffusion-webui-forge-new\webui\backend\sampling\sampling_function.py", line 362, in sampling_function
    denoised, cond_pred, uncond_pred = sampling_function_inner(model, x, timestep, uncond, cond, cond_scale, model_options, seed, return_full=True)
  File "D:\stable-diffusion\stable-diffusion-webui-forge-new\webui\backend\sampling\sampling_function.py", line 303, in sampling_function_inner
    cond_pred, uncond_pred = calc_cond_uncond_batch(model, cond, uncond_, x, timestep, model_options)
  File "D:\stable-diffusion\stable-diffusion-webui-forge-new\webui\backend\sampling\sampling_function.py", line 273, in calc_cond_uncond_batch
    output = model.apply_model(input_x, timestep_, **c).chunk(batch_chunks)
  File "D:\stable-diffusion\stable-diffusion-webui-forge-new\webui\backend\modules\k_model.py", line 45, in apply_model
    model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options, **extra_conds).float()
  File "D:\stable-diffusion\stable-diffusion-webui-forge-new\system\python\lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\stable-diffusion\stable-diffusion-webui-forge-new\system\python\lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\stable-diffusion\stable-diffusion-webui-forge-new\webui\backend\nn\unet.py", line 713, in forward
    h = module(h, emb, context, transformer_options)
  File "D:\stable-diffusion\stable-diffusion-webui-forge-new\system\python\lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\stable-diffusion\stable-diffusion-webui-forge-new\system\python\lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\stable-diffusion\stable-diffusion-webui-forge-new\webui\backend\nn\unet.py", line 83, in forward
    x = layer(x, context, transformer_options)
  File "D:\stable-diffusion\stable-diffusion-webui-forge-new\system\python\lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\stable-diffusion\stable-diffusion-webui-forge-new\system\python\lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\stable-diffusion\stable-diffusion-webui-forge-new\webui\backend\nn\unet.py", line 321, in forward
    x = block(x, context=context[i], transformer_options=transformer_options)
  File "D:\stable-diffusion\stable-diffusion-webui-forge-new\system\python\lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\stable-diffusion\stable-diffusion-webui-forge-new\system\python\lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\stable-diffusion\stable-diffusion-webui-forge-new\webui\backend\nn\unet.py", line 181, in forward
    return checkpoint(self._forward, (x, context, transformer_options), None, self.checkpoint)
  File "D:\stable-diffusion\stable-diffusion-webui-forge-new\webui\backend\nn\unet.py", line 12, in checkpoint
    return f(*args)
  File "D:\stable-diffusion\stable-diffusion-webui-forge-new\webui\backend\nn\unet.py", line 267, in _forward
    n = self.attn2(n, context=context_attn2, value=value_attn2, transformer_options=extra_options)
  File "D:\stable-diffusion\stable-diffusion-webui-forge-new\system\python\lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\stable-diffusion\stable-diffusion-webui-forge-new\system\python\lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\stable-diffusion\stable-diffusion-webui-forge-new\webui\extensions\sd-forge-layerdiffuse\lib_layerdiffusion\attention_sharing.py", line 129, in forward
    x = attention.attention_function(q, k, v, self.heads)
  File "D:\stable-diffusion\stable-diffusion-webui-forge-new\webui\backend\attention.py", line 335, in attention_pytorch
    out = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=mask, dropout_p=0.0, is_causal=False)
RuntimeError: CUDA error: invalid configuration argument
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

Would be a great help if possible to resolve!

**Comment by Haoming02** [comment]
Wait, does `LayerDiffuse` support `Hires. fix` now?

iirc it didn't when on release

**Comment by Thyranix** [comment]
it did not on release, yeah but it did get added later.
If i disable Couple the image is also generated fine, so it has to be something where Couple and LayerDiffuse disagree with eachother

**Comment by Haoming02** [comment]
Got it. I'll try looking into it.

**Comment by Thyranix** [comment]
i played around some more and it seems somehow the number of lines I have in the prompt is relevant as well as the "upscale by" factor selected in hires.fix.

for example - the same image works with hires.fix  + couple enabled only if there is either 1, 3 or 4 (didnt test more) lines in my prompt, if there are 2 lines in the prompt the generation fails.

Also it seems setting the upscaling factor to anything above 2.3 causes the generation to fail - im running on a 4090 so performance/VRAM shouldnt be a problem.

**Comment by Haoming02** [comment]
Added a new checkbox to disable this Extension during `Hires. fix`, please give it a try~

**Comment by Thyranix** [comment]
works fine now, thanks!

there are some other issues with trying to generate multiple images in a batch, but im not sure if couple or layerdiffusion is the issue here. strangely batches of 5 seem to work most of the time.

**Comment by Haoming02** [comment]
> batches of 5

Sheesh, what GPU do you have that you can run 5 images with `Hires. fix` at once XD
