### ISSUE TITLE
sd-forge-couple stops working in Reforge 

### ISSUE THREAD

**Issue by metapea** [Haoming02/sd-forge-couple#77]
With the new commit (https://github.com/Haoming02/sd-forge-couple/commit/d157041bf7de425761fdf84611d9e358959cb066), sd-forge-couple doesn't show up in reforge and gives an error:
```shell 
*** Error loading script: forge_couple.py
    Traceback (most recent call last):
      File "X:\Reforge\webui\modules\scripts.py
", line 524, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "X:\Reforge\webui\modules\script_loa
ding.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_remov
ed
      File "X:\Reforge\webui\extensions\sd-forg
e-couple\scripts\forge_couple.py", line 13, in <module>
        from lib_couple.ui import couple_ui
      File "X:\Reforge\webui\extensions\sd-forg
e-couple\lib_couple\ui.py", line 2, in <module>
        from .ui_adv import advanced_ui
      File "X:\Reforge\webui\extensions\sd-forg
e-couple\lib_couple\ui_adv.py", line 12, in <module>
        PresetManager.load_presets()
      File "X:\Reforge\webui\extensions\sd-forg
e-couple\lib_couple\adv_presets.py", line 17, in load_presets
        cls.presets = load(json_file)
      File "json\__init__.py", line 293, in load
      File "json\__init__.py", line 346, in loads
      File "json\decoder.py", line 337, in decode
      File "json\decoder.py", line 355, in raw_decode
    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
https://github.com/Haoming02/sd-forge-couple/commit/3925bc756e6bb221ee2b6326aea1594d40519953 still works in Reforge.
I'm unsure if it's from your side or reforge side so i'm reporting this here as well.

**Comment by metapea** [comment]
> Try deleting the `presets.json` file in the extension folder.

Worked

**Comment by Haoming02** [comment]
Nah, adding `{}` fixes the issue. If you launched the Webui using the last version, it would've generated an empty file, which isn't a valid JSON, hence the error.
